"""Measure how well the court separates real edges from noise, and how fast it is.

    python scripts/calibrate.py                 # made-up data only
    python scripts/calibrate.py --real          # also every saved Bitget snapshot
    python scripts/calibrate.py --out docs/calibration.md

Checks (from the PRD's success metrics):
* Fake-edge rejection: random prices should FAIL at least 95% of the time.
* Real-edge acceptance: prices with a planted trend should let a trend rule PASS.
* Same input, same ruling: every case is run twice and compared.
* Time to ruling: under 10 seconds (measured per ruling).
"""

from __future__ import annotations

import argparse
import sys
import time
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import numpy as np  # noqa: E402

from lotcouncil.court import DEFAULT_THRESHOLDS, CourtError, market_from_frame, public_ruling, run_court  # noqa: E402
from lotcouncil.data import SNAPSHOT_DIR, load_snapshot  # noqa: E402
from tests import synthetic  # noqa: E402

RULES = {
    "average cross 10/40": {"type": "ma_cross", "fast": 10, "slow": 40},
    "average cross 24/120": {"type": "ma_cross", "fast": 24, "slow": 120},
    "breakout 48h": {"type": "breakout", "lookback": 48},
    "dip buy 1.5%": {"type": "dip_buy", "drop_pct": 1.5, "lookback": 24, "max_hold": 24},
}


def judge(df, rule):
    t0 = time.perf_counter()
    r = run_court(market_from_frame(df), rule)
    return r, time.perf_counter() - t0


def batch(make, seeds, days, label, lines, timings, determinism):
    counts = {name: Counter() for name in RULES}
    for seed in seeds:
        df = make(seed=seed).tail(days * 24)
        for name, rule in RULES.items():
            r, dt = judge(df, rule)
            timings.append(dt)
            c = counts[name]
            c["n"] += 1
            c[r["verdict"]] += 1
            if not r["gate"]["passed"]:
                c["gate"] += 1
            for k, t in r["tests"].items():
                c[k + "_pass"] += t["passed"]
            if seed == seeds[0]:
                again, _ = judge(df, rule)
                determinism.append(public_ruling(again) == public_ruling(r))
    lines.append(f"\n### {label}\n")
    lines.append("| Rule | Rulings | PASS rate | Too few trades | A passed | B passed | C passed |")
    lines.append("| --- | --- | --- | --- | --- | --- | --- |")
    total = Counter()
    for name, c in counts.items():
        judged = c["n"] - c["gate"]
        lines.append(
            f"| {name} | {c['n']} | {100 * c['PASS'] / c['n']:.1f}% | {c['gate']} | "
            + " | ".join(f"{c[k + '_pass']}/{judged}" for k in "ABC")
            + " |"
        )
        total.update(c)
    lines.append(f"| **all** | {total['n']} | **{100 * total['PASS'] / total['n']:.1f}%** | {total['gate']} | | | |")
    return total


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--series", type=int, default=100, help="made-up series per market type")
    ap.add_argument("--days", type=int, default=90)
    ap.add_argument("--real", action="store_true", help="also judge every saved Bitget snapshot")
    ap.add_argument("--out", help="write the report to this markdown file")
    args = ap.parse_args()

    lines = [
        "# Court calibration report",
        "",
        f"Generated by `scripts/calibrate.py --series {args.series} --days {args.days}`. "
        f"Window: last {args.days} days of hourly candles. Fee 0.10%. Thresholds: "
        + ", ".join(f"{k}={v:g}" for k, v in DEFAULT_THRESHOLDS.items())
        + ".",
    ]
    timings: list[float] = []
    determinism: list[bool] = []
    seeds = list(range(1000, 1000 + args.series))

    noise = batch(synthetic.random_walk, seeds, args.days, "Random prices (no edge, normal returns)", lines, timings, determinism)
    fat = batch(synthetic.clustered_walk, seeds, args.days, "Random prices (no edge, fat tails and volatility clusters)", lines, timings, determinism)
    trend = batch(synthetic.trending, seeds, args.days, "Planted trend (a real, made-up edge for trend rules)", lines, timings, determinism)

    fake_pass = (noise["PASS"] + fat["PASS"]) / (noise["n"] + fat["n"])
    lines += [
        "",
        "## Summary",
        "",
        f"- **Fake-edge rejection:** random prices failed {100 * (1 - fake_pass):.1f}% of "
        f"{noise['n'] + fat['n']} rulings (target: 95% or more).",
        f"- **Real-edge acceptance:** on planted-trend prices, {100 * trend['PASS'] / trend['n']:.1f}% of all rulings passed "
        "(trend rules should pass often; the dip-buy rule bets against trends and should not).",
        f"- **Same input, same ruling:** {sum(determinism)}/{len(determinism)} repeated rulings matched exactly.",
        f"- **Time to ruling:** median {1000 * np.median(timings):.0f} ms, slowest {1000 * max(timings):.0f} ms "
        f"over {len(timings)} rulings of {args.days * 24} candles (target: under 10 s).",
    ]

    if args.real:
        lines += ["", "## Saved Bitget candles", ""]
        files = sorted(SNAPSHOT_DIR.glob("*.csv"))
        if not files:
            lines.append("No snapshots found. Run `python scripts/fetch_candles.py` from a host that can reach Bitget.")
        else:
            lines += ["| Token | Candles | First | Last | " + " | ".join(RULES) + " |", "| --- " * (4 + len(RULES)) + "|"]
            for f in files:
                df = load_snapshot(f.stem)
                df = df.tail(args.days * 24)
                cells = []
                for rule in RULES.values():
                    try:
                        r, dt = judge(df, rule)
                        timings.append(dt)
                        failed = "".join(k for k, t in r["tests"].items() if not t["passed"]) or ("gate" if not r["gate"]["passed"] else "")
                        cells.append(r["verdict"] + (f" ({failed})" if failed else ""))
                    except CourtError as e:
                        cells.append(f"error: {e}"[:40])
                first = np.datetime64(int(df["time"].iloc[0]), "ms")
                last = np.datetime64(int(df["time"].iloc[-1]), "ms")
                lines.append(f"| {f.stem} | {len(df)} | {first} | {last} | " + " | ".join(cells) + " |")

    report = "\n".join(lines) + "\n"
    print(report)
    if args.out:
        Path(args.out).write_text(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
